config/routes.rb
Rails.application.routes.draw do

  root 'items#index'
  devise_for :users, skip: :all
  devise_scope :user do
    get 'login', to: 'users/sessions#new', as: :new_user_session
    post 'login', to: 'users/sessions#create'
    get 'signup', to: 'users/registrations#index', as: :index_user_registration
    get 'signup/registration', to: 'users/registrations#new', as: :new_user_registration
    post 'signup/registration', to: 'users/registrations#create'
    delete 'signup', to: 'users/sessions#destroy', as: :destroy_session
    get 'signup/complete', to: 'devise/registrations#complete', as: :new_user_complete
  end

  resources :registrations

  resources :users, only: [:index, :show, :update] do
    collection do
      get 'logout'
    end
  end

  resource :items do
    collection do
      get 'get_category_ms'
      get 'get_category_ss'
      get 'deal'
      get 'completion'
      # /profiles/get_cities
    end
  end

  resource :deals do
    get 'dealing'
    get 'completion'
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :seller_deals, class_name: "Deal", foreign_key: "seller_id", dependent: :destroy
  has_many :buyer_deals, class_name: "Deal", foreign_key: "buyer_id", dependent: :destroy
  has_many :items, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :deals
  has_many :deals_messages
  has_many :comments, dependent: :destroy
  has_many :selling_items, -> { where("buyer_id is NULL") }, class_name: "Item", foreign_key: "seller_id"
  has_many :sold_items, -> { where("buyer_id is not NULL") }, class_name: "Item", foreign_key: "seller_id"
  has_many :bought_items, class_name: "Item", foreign_key: "seller_id"

  enum prefecture: {
    '北海道': 1,
    '青森県': 2,
    '岩手県': 3,
    '宮城県': 4,
    '秋田県': 5,
    '山形県': 6,
    '福島県': 7,
    '茨城県': 8,
    '栃木県': 9,
    '群馬県': 10,
    '埼玉県': 11,
    '千葉県': 12,
    '東京都': 13,
    '神奈川県': 14,
    '新潟県': 15,
    '富山県': 16,
    '石川県': 17,
    '福井県': 18,
    '山梨県': 19,
    '長野県': 20,
    '岐阜県': 21,
    '静岡県': 22,
    '愛知県': 23,
    '三重県': 24,
    '滋賀県': 25,
    '京都府': 26,
    '大阪府': 27,
    '兵庫県': 28,
    '奈良県': 29,
    '和歌山県': 30,
    '鳥取県': 31,
    '島根県': 32,
    '岡山県': 33,
    '広島県': 34,
    '山口県': 35,
    '徳島県': 36,
    '香川県': 37,
    '愛媛県': 38,
    '高知県': 39,
    '福岡県': 40,
    '佐賀県': 41,
    '長崎県': 42,
    '熊本県': 43,
    '大分県': 44,
    '宮崎県': 45,
    '鹿児島県': 46,
    '沖縄県': 47,
    }
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to registrations_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :nickname)
  end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  before_action :authenticate_user!, only: [:create]

  def create
    redirect_to root_path if user_signed_in?
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_group, only: [:index, :logout]

  def index
  end

  def show
  end

  def logout
  end

 private

  def set_group
    @user = current_user.id
  end

end

app/views/users/_creditcard.html.haml
= render 'items/header'
= render 'users/sidebar'
%main.l-container.clearfix
  %main.mypage.clearfix
    .credit-content
      %section.chapter-container
        .h2.chapter-container__title 支払い方法
      %section.credit-content-inner
        .h3.chapter-sub-container__c-title クレジットカード一覧
        %section.set-credit-content
          .button.btn-default.btn-red{type: "submit"} クレジットカードを追加する
        %section.set-regist
          %a
            支払い方法について
= render 'items/footbanner'
= render 'items/footer'

app/views/users/_deal.html.haml
.deal-header
  %t1
    =link_to root_path, class: "mercari-home" do
      =image_tag "logo.svg",width:"185",height:"49"
.wrap#deals_new
  %main.single-main
    %section.l-single-container.buy-item-container
      %h2.l-single-head 購入を確定しますか？
      %section.buy-content.buy-item
        .buy-content-inner
          %h3.buy-item-image
            %img.lazyload{alt: "", src: "https://static-mercari-jp-imgtr2.akamaized.net/thumb/photos/m70068440240_1.jpg?1539045823"}/
          %p.buy-item-name.bold レア！【新品未使用】エアラインキャップ カンタス航空
          %form.buy-form{action: "https://www.mercari.com/jp/transaction/buy/done/m70068440240/", method: "POST", novalidate: "novalidate"}
            %p.buy-price-ja.bold
              ¥ 3,980
              %span.item-shipping-fee.f14.bold 送料込み
            %ul.buy-accordion.not-have
              %li.accordion-parent
                .accordion-toggle
                  ポイントはありません
            %ul.buy-price-table
              %li.buy-price-row.buy-you-pay.bold
                .buy-price-cell 支払い金額
                .buy-price-cell
                  %span
            %button.btn-default.btn-red.bold{type: "submit"} 購入する
      %section.buy-content.buy-user-info
        .buy-content-inner
          %h3 配送先
          %address.buy-user-info-text
            〒114-0000
            %br/
            東京都 渋谷区渋谷川
            1-23-4
            %br/
            山田 太郎
          %p.buy-user-info-text
          = link_to '#', class: "buy-user-info-fix" do
            %span 変更する
            = fa_icon "angle-right"
      %section.buy-content.buy-user-info{data: {buy: "pay-method"}}
        .buy-content-inner
          %h3 支払い方法
          %p.buy-user-info-text
            ************9999
            %br/
            12 / 31
            %figure
              %img{alt: "visa", height: "15", src: "//www-mercari-jp.akamaized.net/assets/img/card/visa.svg?582886128", width: "49"}/
          = link_to '#', class: "buy-user-info-fix" do
            %span 変更する
            = fa_icon "angle-right"

app/views/users/_mypage.html.haml
= render 'items/header'
- breadcrumb :user_mypage
= render './breadcrumb'
= render partial: 'users/sidebar'
%main.l-container.clearfix
  %section.user-icon
    %a
      %figure
        = image_tag "user_photo_noimage.png", size: "50x50", class: "icon_image"
        %h2.bold name
      .user-number
        %div
          評価
          %span.bold -
        %div
          出品数
          %span.bold -
  %section.notification-todo
    %ul.notification-todo__tabs
      %li.active
        %h3
          %a
            お知らせ
      %li
        %h3
          %a
            やることリスト
    %ul.notification__content
      %li
        %a.notification-todo__content-link
          =image_tag "mercari_profile.png", class: "mercari_icon"
          .notification-todo__content-link--text
            message
          %time
            %i.far.fa-clock.my-gray
            %span - 日前
            %i.fas.fa-angle-right.fa-lg
      %li
        %a.notification-todo__content-link
          =image_tag "mercari_profile.png", class: "mercari_icon"
          .notification-todo__content-link--text
            message
          %time
            %i.far.fa-clock.my-gray
            %span - 日前
            %i.fas.fa-angle-right.fa-lg
      %li
        %a.notification-todo__content-link
          =image_tag "mercari_profile.png", class: "mercari_icon"
          .notification-todo__content-link--text
            message
          %time
            %i.far.fa-clock.my-gray
            %span - 日前
            %i.fas.fa-angle-right.fa-lg
      %li
        %a.notification-todo__content-link
          =image_tag "mercari_profile.png", class: "mercari_icon"
          .notification-todo__content-link--text
            message
          %time
            %i.far.fa-clock.my-gray
            %span - 日前
            %i.fas.fa-angle-right.fa-lg
      %li.mypage-go-list
        %a 一覧を見る
    -# %ul.todo__content
    -#   %li
    -#     現在やることはありません
  %section.past-dealings-container
    %h2.past-dealings-container__head
      購入した商品
    %ul.past-dealings-container__tabs
      %li.active
        %h3
          %a
            取引中
      %li
        %h3
          %a
            過去の取引
    .past-dealings-container__content
      =image_tag "background_logo.svg", class: "mercari_gray_icon"
      取引中の商品がありません

= render 'items/footbanner'
= render 'items/footer'
= render 'items/new_item_btn'

app/views/users/_profile.html.haml
= render 'items/header'

.bigbox
  = render 'users/sidebar'
  %main.l-container.clearfix
    %main.mypage.clearfix
      .l-content
        %section.chapter-container
          %h2.chapter-container__title プロフィール
          %form{action: ""}
            %input{type: "hidden"}/
            .profile-icon
              .profile-icon__content
                %image.icon
                  = image_tag "user_photo_noimage.png", size: "50x50", class: "icon_image"
                %input.input-name{type: "text", value: "asuka"}/
            .profile-text
              %textarea.textarea-default{name: "introduction", cols: "20", rows: "10", placeholder: "例）こんにちは☆ ご覧いただきありがとうございます！かわいいものやきれいめオフィスカジュアル中心に出品しています。服のサイズは主に9号です。気持ちよくお取引できるよう心がけていますので、商品や発送方法などご質問がありましたらお気軽にどうぞ♪"}
              %input{type: "hidden"}/
              %button.btn-default.btn-red{type: "submit"} 変更する
= render 'items/footbanner'
= render 'items/footer'

app/views/users/_sidebar.html.haml
.default-container
  .l-side.clearfix
    %nav.mypage-nav
      %ul.mypage-nav-list
        %li
          %a.mypage-nav__list--item.active{href: "/jp/mypage/"}
            マイページ
            %i.fas.fa-angle-right.fa-lg
        %li
          %a.mypage-nav__list--item{href: ""}
            お知らせ
            %i.fas.fa-angle-right.fa-lg
        %li
          %a.mypage-nav__list--item{href: ""}
            やることリスト
            %i.fas.fa-angle-right.fa-lg
        %li
          %a.mypage-nav__list--item{href: ""}
            いいね！一覧
            %i.fas.fa-angle-right.fa-lg
        %li
          %a.mypage-nav__list--item{href: ""}
            出品する
            %i.fas.fa-angle-right.fa-lg
        %li
          %a.mypage-nav__list--item{href: ""}
            出品した商品 - 出品中
            %i.fas.fa-angle-right.fa-lg
        %li
          %a.mypage-nav__list--item{href: ""}
            出品した商品 - 取引中
            %i.fas.fa-angle-right.fa-lg
        %li
          %a.mypage-nav__list--item{href: ""}
            出品した商品 - 売却済み
            %i.fas.fa-angle-right.fa-lg
        %li
          %a.mypage-nav__list--item{href: ""}
            購入した商品 - 取引中
            %i.fas.fa-angle-right.fa-lg
        %li
          %a.mypage-nav__list--item{href: ""}
            購入した商品 - 過去の取引
            %i.fas.fa-angle-right.fa-lg
        %li
          %a.mypage-nav__list--item{href: ""}
            ニュース一覧
            %i.fas.fa-angle-right.fa-lg
        %li
          %a.mypage-nav__list--item{href: ""}
            評価一覧
            %i.fas.fa-angle-right.fa-lg
        %li
          %a.mypage-nav__list--item{href: "/"}
            ガイド
            %i.fas.fa-angle-right.fa-lg
        %li
          %a.mypage-nav__list--item{href: ""}
            お問い合わせ
            %i.fas.fa-angle-right.fa-lg
      %h3.mypage-nav__head 売上・ポイント
      %ul.mypage-nav__list
        %li
          %a.mypage-nav__list--item{href: ""}
            売上・振込申請
            %i.fas.fa-angle-right.fa-lg
        %li
          %a.mypage-nav__list--item{href: ""}
            ポイント
            %i.fas.fa-angle-right.fa-lg
      %h3.mypage-nav__head 設定
      %ul.mypage-nav__list
        %li
          %a.mypage-nav__list--item{href: ""}
            プロフィール
            %i.fas.fa-angle-right.fa-lg
        %li
          %a.mypage-nav__list--item{href: ""}
            住所変更
            %i.fas.fa-angle-right.fa-lg
        %li
          %a.mypage-nav__list--item{href: ""}
            支払い方法
            %i.fas.fa-angle-right.fa-lg
        %li
          %a.mypage-nav__list--item{href: ""}
            メール/パスワード
            %i.fas.fa-angle-right.fa-lg
        %li
          %a.mypage-nav__list--item{href: ""}
            本人情報
            %i.fas.fa-angle-right.fa-lg
        %li
          %a.mypage-nav__list--item{href: ""}
            電話番号の確認
            %i.fas.fa-angle-right.fa-lg
        %li
          = link_to logout_users_path, class: "a mypage-nav__list--item" do
            %i.fas.fa-angle-right.fa-lg
            ログアウト

app/views/users/index.html.haml
= render 'users/mypage'

app/views/users/logout.html.haml
= render 'items/header'
= render 'users/sidebar'
.l-container.clearfix
  .mypage.clearfix
    .logout-content
      .chapter-container
        .form-section
          = link_to destroy_session_path, method: :delete do
            %button.logout-red ログアウト
= render 'items/new_item_btn'
= render 'items/footbanner'
= render 'items/footer'

app/views/users/show.html.haml
.header
  = render 'items/header'

.body
  = render 'users/sidebar'

%main.profile-container.clearfix
  %section
    %figure
      %div
        %span.bold
      %div
        %span.bold
  %section.edit-address
    %ul.edit-address__tabs
      %li.active
        %h3.account-information
          本人情報の登録
          .require_text
            お客さまのあんしん・あんぜんな取引のため、本人情報のご登録をお願いしております。

    %ul.notification__content
      %li
        %a.notification-todo__content-link
          .notification-todo__content-link--text

        %form.inner{:action => "", :method => "POST", :novalidate => ""}
          .form-group
            %label 住所
            %span.form-require 必須
            .address-info
              %address
                %p 〒111-1111
                %p 東京都東京都目黒区1-2-3マンション目黒101
                %p 山田　太郎
                %a{:href => ""} 編集


            .clearfix
          .form-group
            %label{:for => "birthday"} 生年月日
            %span.form-require 必須
            %br/
            .birthday-select-wrap
              .select-wrap
                %select.select-default{:name => "year"}
                  %option{:value => ""} --
                  %option{:value => "1951"} 1951
                  %option{:value => "1952"} 1952
                  %option{:value => "1953"} 1953
                  %option{:value => "1954"} 1954
                  %option{:value => "1955"} 1955
                  %option{:value => "1956"} 1956
                  %option{:value => "1957"} 1957
                  %option{:value => "1958"} 1958
                  %option{:value => "1959"} 1959
                  %option{:value => "1960"} 1960
                  %option{:value => "1961"} 1961
                  %option{:value => "1962"} 1962
                  %option{:value => "1963"} 1963
                  %option{:value => "1964"} 1964
                  %option{:value => "1965"} 1965
                  %option{:value => "1966"} 1966
                  %option{:value => "1967"} 1967
                  %option{:value => "1968"} 1968
                  %option{:value => "1969"} 1969
                  %option{:value => "1970"} 1970
                  %option{:value => "1971"} 1971
                  %option{:value => "1972"} 1972
                  %option{:value => "1973"} 1973
                  %option{:value => "1974"} 1974
                  %option{:value => "1975"} 1975
                  %option{:value => "1976"} 1976
                  %option{:value => "1977"} 1977
                  %option{:value => "1978"} 1978
                  %option{:value => "1979"} 1979
                  %option{:value => "1980"} 1980
                  %option{:value => "1981"} 1981
                  %option{:value => "1982"} 1982
                  %option{:value => "1983"} 1983
                  %option{:value => "1984"} 1984
                  %option{:value => "1985"} 1985
                  %option{:value => "1986"} 1986
                  %option{:value => "1987"} 1987
                  %option{:value => "1988"} 1988
                  %option{:value => "1989"} 1989
                  %option{:value => "1990"} 1990
                  %option{:value => "1991"} 1991
                  %option{:value => "1992"} 1992
                  %option{:value => "1993"} 1993
                  %option{:value => "1994"} 1994
                  %option{:value => "1995"} 1995
                  %option{:value => "1996"} 1996
                  %option{:value => "1997"} 1997
                  %option{:value => "1998"} 1998
                  %option{:value => "1999"} 1999
                  %option{:value => "2000"} 2000
                  %option{:value => "2001"} 2001
                  %option{:value => "2002"} 2002
                  %option{:value => "2003"} 2003
                  %option{:value => "2004"} 2004
                  %option{:value => "2005"} 2005
                  %option{:value => "2006"} 2006
                  %option{:value => "2007"} 2007
                  %option{:value => "2008"} 2008
                  %option{:value => "2009"} 2009
                  %option{:value => "2010"} 2010
                  %option{:value => "2011"} 2011
                  %option{:value => "2012"} 2012
                  %option{:value => "2013"} 2013
                  %option{:value => "2014"} 2014
                  %option{:value => "2015"} 2015
                  %option{:value => "2016"} 2016
                  %option{:value => "2017"} 2017
                  %option{:value => "2018"} 2018
                %i.icon-arrow-bottom
              %span.date 年
            .birthday-select-wrap
              .select-wrap.select-wrap__month
                %select.select-default{:name => "month"}
                  %option{:value => ""} --
                  %option{:value => "1"} 1
                  %option{:value => "2"} 2
                  %option{:value => "3"} 3
                  %option{:value => "4"} 4
                  %option{:value => "5"} 5
                  %option{:value => "6"} 6
                  %option{:value => "7"} 7
                  %option{:value => "8"} 8
                  %option{:value => "9"} 9
                  %option{:value => "10"} 10
                  %option{:value => "11"} 11
                  %option{:value => "12"} 12
                %i.icon-arrow-bottom
              %span.date 月
            .birthday-select-wrap
              .select-wrap.select-wrap__day
                %select.select-default{:name => "day"}
                  %option{:value => ""} --
                  %option{:value => "1"} 1
                  %option{:value => "2"} 2
                  %option{:value => "3"} 3
                  %option{:value => "4"} 4
                  %option{:value => "5"} 5
                  %option{:value => "6"} 6
                  %option{:value => "7"} 7
                  %option{:value => "8"} 8
                  %option{:value => "9"} 9
                  %option{:value => "10"} 10
                  %option{:value => "11"} 11
                  %option{:value => "12"} 12
                  %option{:value => "13"} 13
                  %option{:value => "14"} 14
                  %option{:value => "15"} 15
                  %option{:value => "16"} 16
                  %option{:value => "17"} 17
                  %option{:value => "18"} 18
                  %option{:value => "19"} 19
                  %option{:value => "20"} 20
                  %option{:value => "21"} 21
                  %option{:value => "22"} 22
                  %option{:value => "23"} 23
                  %option{:value => "24"} 24
                  %option{:value => "25"} 25
                  %option{:value => "26"} 26
                  %option{:value => "27"} 27
                  %option{:value => "28"} 28
                  %option{:value => "29"} 29
                  %option{:value => "30"} 30
                  %option{:value => "31"} 31
                %i.icon-arrow-bottom
              %span.date 日
            %p.form-info-text
              ※出品されたことがある、本人情報未登録のお客さまもご対象となります。
            %input{:name => "birthday", :type => "hidden", :value => ""}/
          .clearfix
      %li.update-address
        %a{:href => ""}登録する

      %li.explain
        %a{:href => "https://www.mercari.com/jp/help_center/article/423/"}本人情報の登録について＞

.footer
  = render 'items/footbanner'

  = render 'items/footer'