config/routes.rb
Rails.application.routes.draw do

  root 'items#index'
  devise_for :users, skip: :all
  devise_scope :user do
    get 'login', to: 'users/sessions#new', as: :new_user_session
    post 'login', to: 'users/sessions#create'
    get 'signup', to: 'users/registrations#index', as: :index_user_registration
    get 'signup/registration', to: 'users/registrations#new', as: :new_user_registration
    post 'signup/registration', to: 'users/registrations#create'
    delete 'signup', to: 'users/sessions#destroy', as: :destroy_session
    get 'signup/complete', to: 'devise/registrations#complete', as: :new_user_complete
  end

  resources :registrations

  resources :users, only: [:index, :show, :update] do
    collection do
      get 'logout'
    end
  end

  resource :items do
    collection do
      get 'get_category_ms'
      get 'get_category_ss'
      get 'deal'
      get 'completion'
      # /profiles/get_cities
    end
  end

  resource :deals do
    get 'dealing'
    get 'completion'
  end

end

app/models/deal.rb
class Deal < ApplicationRecord
  belongs_to :item
  belongs_to :seller, class_name: "User", foreign_key: :seller_id
  belongs_to :buyer, class_name: "User", foreign_key: :buyer_id
  has_many :deal_messages, dependent: :destroy
end

app/controllers/deals_controller.rb
class DealsController < ApplicationController

  def index
  end

  def dealing
  end

  def completion
  end

end

app/views/deals/completion.html.haml
.deal-header
  %t1
    =link_to root_path, class: "mercari-home" do
      =image_tag "logo.svg",width:"185",height:"49"
.wrap#deals_new
  %main.single-main
    %section.l-single-container.buy-item-container
      %h2.l-single-head お支払いが完了しました
      %section.buy-content.buy-item
        .section.btn-content
        = link_to root_path, class: "mercari-home" do
          .button.btn-default.btn-red.bold{type: "submit"} トップへ戻る
= render 'shared/login_footer'

app/views/deals/dealing.html.haml
.deal-header
  %t1
    =link_to root_path, class: "mercari-home" do
      =image_tag "logo.svg",width:"185",height:"49"
.wrap#deals_new
  %main.single-main
    %section.l-single-container.buy-item-container
      %h2.l-single-head 購入を確定しますか？
      %section.buy-content.buy-item
        .buy-content-inner
          %h3.buy-item-image
            %img.lazyload{alt: "", src: "https://static-mercari-jp-imgtr2.akamaized.net/item/detail/orig/photos/m70068440240_1.jpg?1539045823", size: "300x300", class: "owl-lazy"}/
          %p.buy-item-name.bold レア！【新品未使用】エアラインキャップ カンタス航空
          %form.buy-form{href: "/items/deals/completion"}
            %p.buy-price-ja.bold
              ¥ 3,980
              %span.item-shipping-fee.f14.bold 送料込み
            %ul.buy-accordion.not-have
              %li.accordion-parent
                .accordion-toggle
                  ポイントはありません
            %ul.buy-price-table
              %li.buy-price-row.buy-you-pay.bold
                .buy-price-cell 支払い金額
                .buy-price-cell
                  %span
            = link_to "購入する", completion_deals_path, class: "button btn-default btn-red bold"
      %section.buy-content.buy-user-info
        .buy-content-inner
          %h3 配送先
          %address.buy-user-info-text
            〒114-0000
            %br/
            東京都 渋谷区渋谷川
            1-999
            %br/
            紺野 衣里
          %p.buy-user-info-text
          = link_to '#', class: "buy-user-info-fix" do
            %span 変更する
            = fa_icon "angle-right"
      %section.buy-content.buy-user-info{data: {buy: "pay-method"}}
        .buy-content-inner
          %h3 支払い方法
          %p.buy-user-info-text
            ****************
            %br/
            4 / 5
            %figure
              %img{alt: "visa", height: "15", src: "//www-mercari-jp.akamaized.net/assets/img/card/visa.svg?582886128", width: "49"}/
          = link_to '#', class: "buy-user-info-fix" do
            %span 変更する
            = fa_icon "angle-right"
= render 'shared/login_footer'

app/views/deals/index.html.haml
= render 'deals/dealing'
= render 'deals/completion'