config/routes.rb
Rails.application.routes.draw do

  root 'items#index'
  devise_for :users, skip: :all
  devise_scope :user do
    get 'login', to: 'users/sessions#new', as: :new_user_session
    post 'login', to: 'users/sessions#create'
    get 'signup', to: 'users/registrations#index', as: :index_user_registration
    get 'signup/registration', to: 'users/registrations#new', as: :new_user_registration
    post 'signup/registration', to: 'users/registrations#create'
    delete 'signup', to: 'users/sessions#destroy', as: :destroy_session
    get 'signup/complete', to: 'devise/registrations#complete', as: :new_user_complete
  end

  resources :registrations

  resources :users, only: [:index, :show, :update] do
    collection do
      get 'logout'
    end
  end

  resource :items do
    collection do
      get 'get_category_ms'
      get 'get_category_ss'
      get 'deal'
      get 'completion'
      # /profiles/get_cities
    end
  end

  resource :deals do
    get 'dealing'
    get 'completion'
  end

end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :seller_deal, class_name: "User", foreign_key: "seller_id"
  belongs_to :buyer_deal, class_name: "User", foreign_key: "buyer_id"
  has_many :likes, dependent: :destroy
  has_many :images, dependent: :destroy
  belongs_to :category_s
  belongs_to :category_m
  belongs_to :category_l
  has_one :deal
  belongs_to :brand
  belongs_to :size


  validates :price,        presence: true, numericality: { greater_than_or_equal_to: 300,
                                                           less_than_or_equal_to: 9999999 }


end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
  end


  def new
    @item = Item.new
   end

  # Ajax処理を行う処理
  def get_category_ms
    render partial: 'select_category_m', locals: {category_l_id: params[:category_l_id]}
  end

  def get_category_ss
    render partial: 'select_category_s', locals: {category_m_id: params[:category_m_id]}
  end

  def show
  end

  def create
    @item = Item.new(item_params)
  end

 private
  def item_params
    params.require(:item).permit(:name, :image_url, :description, :category_l_id, :category_m_id, :category_s_id, :condition, :shipping_fee, :arrived_date, :size_id, :price)
  end

end

app/views/items/_completion.html.haml
.deal-header
  %t1
    =link_to root_path, class: "mercari-home" do
      =image_tag "logo.svg",width:"185",height:"49"
.wrap#deals_new
  %main.single-main
    %section.l-single-container.buy-item-container
      %h2.l-single-head お支払いが完了しました
      %section.buy-content.buy-item
      =link_to root_path, class: "mercari-home" do
        .button.btn-default.btn-red.bold{type: "submit"} トップへ戻る
= render 'shared/login_footer'

app/views/items/_footbanner.html.haml
.bottom-dl-area
  .bottom-dl-area__contents
    .left-img
      %h2
        スマホでかんたんフリマアプリ
      %p
        今すぐ無料ダウンロード！
      .app-banner-icon.clearfix
        %figure.app-banner-icon__icons-box
          = image_tag("https://www-mercari-jp.akamaized.net/assets/img/common/common/mercari_icon.png?1016580576", class: "mercari-icon")
        %ul.imgs.clearfix
          %li
            = image_tag("https://www-mercari-jp.akamaized.net/assets/img/common/common/google-play.svg?1016580576", class: "imgs__store app")
          %li
            = image_tag("https://www-mercari-jp.akamaized.net/assets/img/common/common/google-play.svg?1016580576", class: "imgs__store google")
    .right-img
      = image_tag("https://www-mercari-jp.akamaized.net/assets/img/common/jp/download_content_pc.png?1016580576")

app/views/items/_footer.html.haml
%footer.global-footer
  %nav
    %ul.content
      %li.footer-cell
        %h2.footer-cell__head メルカリについて
        %ul
          %li
            %a{href: "https://about.mercari.com/"} 会社概要（運営会社）
          %li
            %a{href: "https://www.mercari.com/jp/privacy/"}
              プライバシーポリシー
          %li
            %a{href: "https://www.mercari.com/jp/tos/"}
              メルカリ利用規約
          %li
            %a{href: "https://www.mercari.com/jp/tos_paid_point/"} メルカリ利用規約・有償ポイントに関する特約
          %li
            %a{href: "https://www.mercari.com/jp/tos_smartphone_support/"} あんしんスマホサポート制度に関する利用特約
          %li
            %a{href: "https://www.mercari.com/jp/compliance/"} コンプライアンスポリシー
          %li
            %a{href: "https://www.mercari.com/jp/data_security/"} 個人データの安全管理に係る基本方針
          %li
            %a{href: "https://www.mercari.com/jp/tokutei/"} 特定商取引に関する表記
          %li
            %a{href: "https://www.mercari.com/jp/shikin_kessai/"} 資金決済法に基づく表示
          %li
            %a{href: "https://about.mercari.com/csr/safety/"} 法令順守と犯罪抑止のために
          %li
            %a{href: "https://www.mercari.com/jp/jobs/"} 採用情報
      %li.footer-cell
        %h2.footer-cell__head メルカリを見る
        %ul
          %li
            %a{href: "https://www.mercari.com/jp/category/"} カテゴリー一覧
          %li
            %a{href: "https://www.mercari.com/jp/brand/"} ブランド一覧
          %li
            %a{href: "https://www.mercari.com/jp/area/"} 出品地域一覧
          %li
            %a{href: "https://jp-news.mercari.com/", target: "_blank"} 公式ブログ
          %li
            %a{href: "https://twitter.com/mercari_jp", target: "_blank"} 公式Twitter
          %li
            %a{href: "https://www.facebook.com/mercarijp", target: "_blank"} 公式Facebook
      %li.footer-cell
        %h2.footer-cell__head ヘルプ＆ガイド
        %ul
          %li
            %a{href: "https://www.mercari.com/jp/help_center/"} メルカリガイド
          %li
            %a{href: "https://www.mercari.com/jp/logo-guidelines/"} メルカリロゴ利用ガイドライン
          %li
            %a{href: "https://about.mercari.com/press/news/"} お知らせ
          %li
            %a{href: "https://www.mercari.com/jp/rakuraku-mercari/"} らくらくメルカリ便とは
          %li
            %a{href: "https://www.mercari.com/jp/yuyu-mercari/"} ゆうゆうメルカリ便とは
          %li
            %a{href: "https://www.mercari.com/jp/rakuraku-ogata/"} 大型らくらくメルカリ便とは
          %li
            %a{href: "https://www.mercari.com/jp/guide/car/"} 車体取引ガイド
          %li
            %a{href: "https://www.mercari.com/jp/refund-returns/"} 返品・返金ポリシー
          %li
            %a{href: "https://www.mercari.com/jp/safe/description/", :target => "_blank"} メルカリあんしん・あんぜん宣言！
          %li
            %a{href: "https://www.mercari.com/jp/authenticity/"} 偽ブランド品撲滅への取り組み
          %li
            %a{href: "https://www.mercari.com/jp/box/"} メルカリボックス
      %li.footer-cell
        %h2.footer-cell__head 国
        %ul.footer-nav-lang
          %li
            %a{href: "https://www.mercari.com/"}
              %img{alt: "", src: "//www-mercari-jp.akamaized.net/assets/img/common/common/flag_us.png?1528449478", width: "22"}>/
              United States
          %li
            %a{href: "https://www.mercari.com/uk/"}
              %img{alt: "", src: "//www-mercari-jp.akamaized.net/assets/img/common/common/flag_uk.png?1528449478", :width => "22"}>/
              United Kingdom
          %li
            %a.active{href: "https://www.mercari.com/jp/"}
              %img{alt: "", src: "//www-mercari-jp.akamaized.net/assets/img/common/common/flag_jp.png?1528449478", width: "22"}>/
              日本
  %a.footer-logo{href: "https://www.mercari.com/jp/"}
    %img{alt: "mercari", height: "33", src: "//www-mercari-jp.akamaized.net/assets/img/common/common/logo-white.svg?1528449478", width: "124"}/
  %p.footer-copyright
    %small © 2018 Mercari
    %p
    = link_to "　", destroy_session_path, method: :delete

app/views/items/_headbanner.html.haml
%main
  %section#topMain
    %div.headbanner
      .headbanner-content
        %h2
          スマホでかんたん<br>フリマアプリ
        %p
          メルカリはスマホカメラからすぐに出品できる<br>購入時も安心な独自システムのアプリです
        .headbanner-store.clearfix
          %a.pull-left{href: "https://itunes.apple.com/jp/app/id667861049?l=ja&mt=8", target: "_blank"}
            %img{alt: "", src: "//www-mercari-jp.akamaized.net/assets/img/common/common/app-store.svg?3221204175"}/
          %a.pull-left{href: "https://play.google.com/store/apps/details?id=com.kouzoh.mercari&hl=ja", target: "_blank"}
            %img{alt: "", src: "//www-mercari-jp.akamaized.net/assets/img/common/common/google-play.svg?3221204175"}/
      %img{alt: "", src: "//www-mercari-jp.akamaized.net/assets/img/common/jp/top/main_content_pc.png?1016580576"}/

app/views/items/_header.html.haml
.default-containerz
  %header
    .logo-and-search__logo.left-float
      = link_to root_path do
        = image_tag '//www-mercari-jp.akamaized.net/assets/img/common/common/logo.svg?1324730246'
    .search
      %form.logo-and-search__search.right-float
        %input{value:"", placeholder:"キーワードから探す" }
        %i.fa.fa-search
    .lists.clearfix
      .lists__left.left-float
        %ul
          %li.categories
            %h2
              %a{href: ""} カテゴリーから探す
          %li.brands
            %h2
              %a{href: ""} ブランドから探す
    - if user_signed_in?
      .sign-in-after
        .header-user-nav__acount
          = image_tag "user_photo_noimage.png", class: "icon_image"
          = link_to "マイページ", users_path, class: "mypage_icon"
        .header-user-nav__notice
          %i.far.fa-bell
            お知らせ
        .header-user-nav__todo
          %i.fas.fa-check
          %span
            やることリスト
    - else
      .signin-and-signup.right-float
        %ul.account
          %li.signin-btn
            = link_to "ログイン", new_user_session_path, class: "signin-btn__text"
          %li.signup-btn
            = link_to "新規会員登録", new_user_registration_path, class: "signup-btn__text"

app/views/items/_new_item_btn.html.haml
.exhibit
  =link_to new_items_path, "data-turbolinks": false do
    .text
      出品
    %i.fa.fa-camera

app/views/items/_pickup_items.html.haml
.pickup-contents
  %h2.pickup-contents__title
    ピックアップカテゴリー
  %section.items-contents.clearfix
    %h3.items-contents__title
      %a
        レディース 新着アイテム
    .items-box-content.clearfix
      .items-box.one
        %a.detail-page
          = image_tag("https://tk.ismcdn.jp/mwimgs/d/9/960x680/img_d9edba1a1285702a726b8fd82cad1676351172.jpg", class: "detail-page__img")
          .detail-page__body
            %h3.item-name
              日本でたった6台､特注ポルシェ911
            .item-price.clearfix
              ¥ 780
            .tax
              (税込)
      .items-box.two
        %a.detail-page
          = image_tag("https://www.ginzatanaka.co.jp/img/jewelry/diamond/photo00.jpg", class: "detail-page__img")
          .detail-page__body
            %h3.item-name
              GINZA TANAKAのダイヤモンド
            .item-price
              ¥ 1,280
            .tax
              (税込)
      .items-box.three
        %a.detail-page
          = image_tag("http://gold.mmc.co.jp/primer/14.jpg", class: "detail-page__img")
          .detail-page__body
            %h3.item-name
              純金積立
            .item-price
              ¥ 1,333
            .tax
              (税込)
      .items-box.four
        %a.detail-page
          = image_tag("https://rollinn.net/wp-content/uploads/2017/05/private-jet04-830x460.png", class: "detail-page__img")
          .detail-page__body
            %h3.item-name
              プライベートジェット
            .item-price
              ¥ 1,500
            .tax
              (税込)
          %a.showall{href: ""}全ての商品を見る
.pickup-contents
  %h2.pickup-contents__title
    ピックアップブランド
  %section.items-contents.clearfix
    %h3.items-contents__title
      %a
        シャネル 新着アイテム
    .items-box-content.clearfix
      .items-box.one
        %a.detail-page
        = link_to items_path do
          = image_tag("https://static-mercari-jp-imgtr2.akamaized.net/item/detail/orig/photos/m70068440240_1.jpg?1539045823", class: "detail-page__img")
          .detail-page__body
            %h3.item-name
              COACH ショルダーバック
            .item-price.clearfix
              ¥ 2,700
            .tax
              (税込)
      .items-box.two
        %a.detail-page
          = image_tag("https://static-mercari-jp-imgtr2.akamaized.net/thumb/photos/m62952971291_1.jpg?1541932797", class: "detail-page__img")
          .detail-page__body
            %h3.item-name
              CHANEL リップ
            .item-price
              ¥ 2,000
            .tax
              (税込)
      .items-box.three
        %a.detail-page
          = image_tag("https://static-mercari-jp-imgtr2.akamaized.net/thumb/photos/m31879339894_1.jpg?1541929449", class: "detail-page__img")
          .detail-page__body
            %h3.item-name
              シャネルカードケース
            .item-price
              ¥ 16,000
            .tax
              (税込)
      .items-box.four
        %a.detail-page
          = image_tag("https://static-mercari-jp-imgtr2.akamaized.net/thumb/photos/m86994739079_1.jpg?1536886749", class: "detail-page__img")
          .detail-page__body
            %h3.item-name
              CHANEL バッグ
            .item-price
              ¥ 12,000
            .tax
              (税込)
          %a.showall{href: ""}全ての商品を見る

app/views/items/_select_category_m.html.haml
= collection_select :item, :category_m_id, CategoryM.where(category_l_id: category_l_id), :id, :name, { prompt: '----'}, {class: "select-default-sell1", id: "category2"}

app/views/items/_select_category_s.html.haml
= collection_select :item, :category_s_id, CategoryS.where(category_m_id: category_m_id), :id, :name, { prompt: '----'}, {class: "select-default-sell2", id: "category3"}

app/views/items/index.html.haml
.body
    = render 'items/header'

    = render 'items/headbanner'

    = render 'items/pickup_items'

    = render 'items/footbanner'

    = render 'items/footer'

    = render 'items/new_item_btn'

app/views/items/new.html.haml
= render 'shared/login_header'

-# %body
-#   %input#myfile{:type => "file"}/
-#   -# %br/
-#   -# %img#img1{:style => "width:300px;height:300px;"}/

.single-main
  #modal01.preview-modal
    .overLay
      .preview-inner
        #crop_area_box
          %img#crop_image
        #crop_preview
          %img#crop-finish
        .preview-inner-header-left
          写真を切り取る
        %a#preview-modalClose
        %img#canvas{:height => "380", :style => "cursor: grab;", :width => "380"}
          .canvas-outflame
            .canvas-inflame
        %i.fa.fa-camera.small
        %input.input-range-default{:max => "2", :min => "1", :name => "scale", :step => "0.01", :type => "range", :value => "1"}
        %i.fa.fa-camera.big
        .preview-crop-btn
          %a#preview-edit-cancell.preview-btn-left キャンセル
          %a#submitBtn.preview-btn-right 完了
          = stylesheet_link_tag    'cropper.min'
          = javascript_include_tag 'cropper.min'

        -# #crop_area_box
        -#   %img#crop_image
        -# #crop_preview
        -#   %img#crop-finish







  .sell-container
    .sell-container__inner
      = form_for (@item), html:{id: 'sell-form'} do |f|
        .sell-container__inner__head
          %h2
            商品の情報を入力
        .sell-upload-box
          = f.label :image, "出品画像", {class: 'form-label'}
          %span.form-require-sell
            必須
          %p
            最大4枚までアップロードできます

            .sell-upload-box
              .sell-dropbox-container
                .sell-upload-items
                  %ul
                    %li.sell-upload-drop-box#preview1
                      = f.file_field :image_url, class: "sell-upload-drop-file", type: :file
                      %img#img1{:style => "width:138px;height:138px;", class: "img1",}
                        %div#img-edit
                          %a.modalOpen1{:href => "#modal01"} 編集
                        %div#img-delite
                          %a 削除

                    %li.sell-upload-drop-box#preview2
                      = f.file_field :image_url, class: "sell-upload-drop-file", type: :file
                      %img#img2{:style => "width:138px;height:138px;", class: "img2",}
                        %div#img2-edit
                          %a{:href => ""} 編集
                        %div#img2-delite
                          %a 削除
                    %li.sell-upload-drop-box#preview3
                      = f.file_field :image_url, class: "sell-upload-drop-file", type: :file
                      %img#img3{:style => "width:138px;height:138px;", class: "img3",}
                        %div#img3-edit
                          %a{:href => ""} 編集
                        %div#img3-delite
                          %a 削除
                    %li.sell-upload-drop-box#preview4
                      = f.file_field :image_url, class: "sell-upload-drop-file", style: "none", type: :file
                      %img#img4{:style => "width:138px;height:138px;", class: "img4",}
                        %div#img4-edit
                          %a{:href => ""} 編集
                        %div#img4-delite
                          %a 削除




        .sell-content
          .form-group-first#dropArea
            = f.label :name, "商品名", {class: 'form-label'}
            %span.form-require-sell
              必須
            %br
            = f.text_field :name, placeholder: "商品名（必須 40文字まで)", class: "input-default-exhibit"
          .form-group-sell
            = f.label :description, "商品の説明", {class: 'form-label'}
            %span.form-require-sell
              必須
            %br
            = f.text_area :description, placeholder: "商品の説明（必須 1,000文字以内）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライドグレーで傷はありません。あわせやすいのでおすすめです。", class: "input-default", size: "100"





        .sell-content
          %H3.sell-sub-head
            商品の詳細
          .sell-form-box
            .form-group-first
              = f.label :categoru_l, "カテゴリー", {class: 'form-label'}
              %span.form-require-sell 必須
              .select-wrap
                = f.collection_select :category_l_id, CategoryL.all, :id, :name,{ prompt: '----'}, {class: "select-default-sell", id: "category1"}
            .sell-form-box.hidden1
              .select-wrap1
                = render partial: 'select_category_m', locals: {category_l_id: CategoryL.first.id}

            .sell-form-box.hidden2
              .select-wrap2
                = render partial: 'select_category_s', locals: {category_m_id: CategoryM.first.id}

            .sell-form-box.hidden3
              = f.label :size, "サイズ", {class: 'form-label'}
              .select-wrap3
                = f.collection_select :size_id, Size.all, :id, :name, { prompt: '----'}, {class: "select-default-sell", id: "size_id"}

            .form-group-sell
              = f.label :condition, "商品の状態", {class: 'form-label'}
              %span.form-require-sell
                必須
              .select-wrap
                %select.select-default
                  %option{value: "0"} -----
                  %option{value: "1"} 新品、未使用
                  %option{value: "2"} 未使用に近い
                  %option{value: "3"} 目立った傷や汚れはなし
                  %option{value: "4"} やや傷や汚れあり
                  %option{value: "5"} 傷や汚れあり
                  %option{value: "6"} 全体的に状態が悪い
        .sell-content
          %H3.sell-sub-head
            配送について
          .sell-form-box
            .form-group-first
              = f.label :shipping_fee, "配送料の負担", {class: 'form-label'}
              %span.form-require-sell
                必須
              .select-wrap
                %select.select-default
                  %option{value: "0"} -----
                  %option{value: "1"} 着払い(購入者負担)
                  %option{value: "2"} 送料込み(出品者負担)
          .sell-form-box
            .form-group-sell
              = f.label :arrived_date, "発送までの日数", {class: 'form-label'}
              %span.form-require-sell
                必須
              .select-wrap
                %select.select-default
                  %option{value: "0"} -----
                  %option{value: "1"} 1~2日で発送
                  %option{value: "2"} 2~3日で発送
                  %option{value: "3"} 4~7日で発送
        .sell-content
          %H3.sell-sub-head
            販売価格(300〜9,999,999)
          .sell-form-box
            %ul.l-left
              %li.form-group-first
                = f.label :price, "価格", {class: 'form-label'}
                %span.form-require-sell
                  必須
            .input-price
              ¥
              = f.text_field :price, class: "input-price-area", id: "amount", placeholder: "例)300"
          .commision
            .l-left
              販売手数料 (10%)
            .l-right#commission
              ー
          .profits
            .l-left
              販売利益
            .l-right#sales-profit
              ー
        .sell-content
          %p
            禁止されている出品、行為を必ずご確認ください。</br>
            またブランド品でシリアルナンバー等がある場合はご記載ください。偽ブランドの販売は犯罪であり処罰される可能性があります。
          .form-group-sell
            = f.submit "投稿する", class: "btn btn__red", id: "new-item-registration"
            = link_to "もどる", root_path, class: "btn btn__gray"






= render 'shared/login_footer'